# https://github.com/sk-/git-lint config
---
sh:
  extensions:
    - .sh
  shellbang:
    - /bin/sh
    - /bin/bash
  arguments:
    - --format=gcc
  command: shellcheck
  filter: >-
        {filename}:(?P<line>\d+):(?P<column>\d+):
        (?P<severity>.+):
        (?P<message>.+)
        \[(?P<message_id>.+)\]
  installation: "Install shellcheck"

# YAML
yaml:
  extensions:
    - .yaml
    - .yml
  command: yamllint
  arguments:
    - --format
    - parsable
    - --config-data
    - relaxed
  # Matches either:
  # - syntax error, on any line
  # - other error, on a modified line only
  filter: >-
    ^{filename}:(?P<line>{lines}|\d+(?=:\d+:
    \[error\] syntax error:)):(?P<column>\d+):
    \[(?P<severity>\S+)\] (?P<message>.+)$

  installation: Run pip install yamllint.

proselint:
  extensions:
    - .rst
    - .md
    - .txt
  command: proselint
  installation: "pip3 install --user proselint"
  filter: >-
    ^{filename}:(?P<line>\d+):(?P<column>\d+)\:
    (?P<message_id>\S+) (?P<message>.+)$

# Markdown
mdl:
  extensions:
    - .md
  command: mdl
  installation: gem install mdl
  filter: >-
    ^{filename}:(?P<line>\d+):
    (?P<message_id>\S+) (?P<message>.+)$


# Python
pylint:
  extensions:
    - .py
  command: pylint
  shellbang:
    - /usr/bin/env python
    - /usr/bin/env python2.7
    - /usr/bin/env python3
    - /usr/bin/python
    - /usr/bin/python2
    - /usr/bin/python2.7
    - /usr/bin/python3
  arguments:
    - --rcfile={DEFAULT_CONFIGS}/pylintrc
    - --output-format=text
    - >-
      --msg-template='{{abspath}}:{{line}}:{{column}}:
      [{{category}}:{{symbol}}] {{obj}}: {{msg}}'
    - --reports=n
  filter: >-
    ^{filename}:(?P<line>{lines}):((?P<column>\d+):)?
    \[(?P<severity>.+):(?P<message_id>\S+)\]\s+(:
    )?(?P<message>.+)$
  installation: "Run pip install pylint."

pep8:
  extensions:
    - .py
  shellbang:
    - /usr/bin/env python
    - /usr/bin/env python2.7
    - /usr/bin/env python3
    - /usr/bin/python
    - /usr/bin/python2
    - /usr/bin/python2.7
    - /usr/bin/python3
  command: pep8
  arguments:
    - --max-line-length=80
  filter: >-
    ^{filename}:(?P<line>{lines}):((?P<column>\d+):)?
    (?P<message_id>\S+)
    (?P<message>.+)$
  installation: Run pip install pep8.
